"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import BottomNav from "@/components/BottomNav";
import { copyTextSafely } from "@/lib/client-clipboard";
import OtpCodeInput from "@/components/OtpCodeInput";

interface ReferralData {
  partner: null | Record<string, any>;
  agreement?: null | { contractVersion: string; acceptedAt: string };
  stats: null | { clicks: number; activeAttributions: number; totalReferrals: number; qualifiedMatches: number; totals: Record<string,string> };
  payouts: Array<Record<string,any>>;
  live: boolean;
  rollout: "shadow" | "canary" | "public";
  stage: "anonymous" | "link_ready" | "cash_ready";
  missingForCash: Array<"quick_rules"|"contract"|"national_id"|"sheba">;
  quickRules: string[];
}
interface ContractData { title:string;version:string;contentHash:string;content:string;confirmations:string[];agreement?:{acceptedAt:string}|null;partner?:Record<string,any>|null; }

function toman(value: unknown) { try { return `${(BigInt(String(value||0))/BigInt(10)).toLocaleString("fa-IR")} USDT`; } catch { return "۰ USDT"; } }
const inputClass="w-full rounded-2xl border border-white/10 bg-black/25 px-4 py-3 text-sm outline-none focus:border-cyan-400/50";
const REQUIREMENT_LABELS:Record<string,string>={quick_rules:"پذیرش قوانین کوتاه معرفی",contract:"امضای قرارداد کامل با کد تأیید ایمیل",national_id:"ثبت کد ملی در پروفایل",sheba:"ثبت شماره شبا"};

export default function PersonalReferralsPage(){
 const [data,setData]=useState<ReferralData|null>(null);const[contract,setContract]=useState<ContractData|null>(null);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[msg,setMsg]=useState<{ok:boolean;text:string}|null>(null);const[checks,setChecks]=useState<boolean[]>([]);const[name,setName]=useState("");const[otp,setOtp]=useState("");const[otpSent,setOtpSent]=useState(false);const[sheba,setSheba]=useState("IR");const[quickChecksRaw,setQuickChecks]=useState<boolean[]>([]);const[showContract,setShowContract]=useState(false);
 const load=useCallback(async()=>{setLoading(true);try{const[a,b]=await Promise.all([fetch("/api/referrals",{cache:"no-store",credentials:"include"}),fetch("/api/referrals/contract",{cache:"no-store",credentials:"include"})]);if(a.status===401){setData(null);setMsg({ok:false,text:"برای فعال‌سازی لینک معرفی ابتدا وارد حساب Flexa شوید."});return;}const d=await a.json();setData(d);if(b.ok){const c=await b.json();setContract(c);setChecks(new Array(c.confirmations?.length||0).fill(false));if(c.partner?.legalName)setName(c.partner.legalName);}}catch{setMsg({ok:false,text:"دریافت اطلاعات انجام نشد."});}finally{setLoading(false);}},[]);
 useEffect(()=>{load();},[load]);
 const totals=data?.stats?.totals||{};const available=BigInt(totals.available||0);const pending=useMemo(()=>BigInt(totals.pending||0),[totals.pending]);const shadow=useMemo(()=>BigInt(totals.shadow||0),[totals.shadow]);const lifetime=useMemo(()=>BigInt(totals.pending||0)+BigInt(totals.available||0)+BigInt(totals.reserved||0)+BigInt(totals.paid||0),[totals.pending,totals.available,totals.reserved,totals.paid]);
 async function call(url:string,body:Record<string,unknown>,method="POST"){setBusy(true);setMsg(null);try{const r=await fetch(url,{method,credentials:"include",headers:{"Content-Type":"application/json","X-Requested-With":"XMLHttpRequest"},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.error||"عملیات انجام نشد");setMsg({ok:true,text:"عملیات با موفقیت انجام شد."});await load();return j;}catch(e){setMsg({ok:false,text:e instanceof Error?e.message:"عملیات انجام نشد"});return null;}finally{setBusy(false);}}
 async function start(){
  const rules=data?.quickRules||[];
  if(quickChecks.length!==rules.length||quickChecks.some(v=>!v)){setMsg({ok:false,text:"برای دریافت لینک، هر سه مورد را تأیید کن."});return;}
  await call("/api/referrals",{quickRules:quickChecks});
 }
 async function sendOtp(){const j=await call("/api/referrals/contract",{action:"send_otp"});if(j){setOtpSent(true);setMsg({ok:true,text:`کد تأیید به ${j.emailHint||"ایمیل حساب"} ارسال شد.`});if(j.devCode)setOtp(j.devCode);}}
 async function sign(code?:string){await call("/api/referrals/contract",{action:"sign",signerName:name,code:code??otp,confirmations:checks});}
 async function saveSheba(){await call("/api/referrals",{sheba},"PATCH");}
 async function redeem(action:"cash"|"gaming_wallet"){const warning=action==="gaming_wallet"?"تمام موجودی آزادشده به اعتبار غیرقابل‌برداشت مسابقه منتقل می‌شود و قابل بازگشت نیست. ادامه می‌دهی؟":"درخواست برداشت نقدی تمام موجودی آزادشده ثبت شود؟";if(!confirm(warning))return;await call("/api/referrals/redeem",{action});}
 async function copyReferralLink(link:string){const copied=await copyTextSafely(link);setMsg({ok:copied,text:copied?"لینک معرفی با موفقیت کپی شد.":"کپی خودکار در این مرورگر انجام نشد؛ از دکمه اشتراک‌گذاری استفاده کن یا روی لینک نگه دار."});}
 if(loading)return <main className="grid min-h-[100dvh] place-items-center bg-[#07080d] text-white">در حال بارگذاری طرح معرفی...</main>;
 const partner=data?.partner;const stage=data?.stage||"anonymous";const missing=data?.missingForCash||[];
 // Derived, not stored: the server owns the rule list, so the checkbox array
 // is just padded to match it on every render. Avoids a setState-in-effect.
 const ruleCount=data?.quickRules?.length||0;
 const quickChecks=Array.from({length:ruleCount},(_,i)=>quickChecksRaw[i]||false);if(partner?.partnerType==="media")return <main className="grid min-h-[70dvh] place-items-center bg-[#07080d] px-5 text-center text-white"><div><h1 className="text-xl font-black">حساب شما شریک رسانه‌ای است</h1><p className="mt-2 text-sm text-gray-500">همان لینک رسانه برای معرفی و کمیسیون استفاده می‌شود.</p><Link href="/media-partners" className="mt-5 inline-block rounded-xl bg-violet-600 px-5 py-3 text-sm font-black">داشبورد رسانه</Link></div></main>;
 return <main className="relative min-h-[100dvh] overflow-hidden bg-[#07080d] pb-28 text-white" dir="rtl"><div className="pointer-events-none fixed inset-0 bg-[radial-gradient(circle_at_80%_0%,rgba(6,182,212,.17),transparent_32%),radial-gradient(circle_at_5%_40%,rgba(124,58,237,.1),transparent_28%)]"/><header className="relative border-b border-white/[.07] bg-[#0a0b12]/90"><div className="mx-auto flex h-18 max-w-5xl items-center px-4 sm:px-6"><Link href="/" className="flex items-center gap-2.5">{/* eslint-disable-next-line @next/next/no-img-element */}
<img src="/icons/flexa-icon-192.png" alt="Flexa" className="h-11 w-11"/><div><div className="text-[8px] font-black tracking-[.22em] text-cyan-300">GAMENT REFERRALS</div><div className="text-sm font-black">درآمد از معرفی</div></div></Link><Link href="/profile" className="mr-auto rounded-xl border border-white/10 px-3 py-2 text-[10px] font-black">پروفایل</Link></div></header><div className="relative mx-auto max-w-5xl px-4 py-7 sm:px-6">
  <section className="rounded-[32px] border border-cyan-300/15 bg-[linear-gradient(135deg,rgba(6,182,212,.14),rgba(124,58,237,.08),rgba(255,255,255,.02))] p-6 sm:p-9"><span className="rounded-full bg-cyan-500/10 px-3 py-1.5 text-[9px] font-black text-cyan-200">REFER • PLAY • EARN</span><h1 className="mt-5 text-3xl font-black leading-[1.45] sm:text-5xl">دوستات را به Flexa دعوت کن؛ از Matchهای واقعی سهم بگیر</h1><p className="mt-4 max-w-3xl text-xs leading-7 text-gray-400">برای هر Match پولی واجد شرایط فقط یک استخر ۷ هزار USDTی ساخته می‌شود. انتساب ۳۰ روزه است و دو معرف متفاوت هرکدام ۳,۵۰۰ USDT می‌گیرند.</p><div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4">{[["۷,۰۰۰","سقف کل Match"],["۳۰ روز","انتساب"],["۷۲ ساعت","Pending"],["۲۰۰ هزار","حداقل برداشت"]].map(([v,l])=><div key={l} className="rounded-2xl border border-white/[.07] bg-black/15 p-3"><strong className="text-lg text-cyan-200">{v}</strong><span className="mt-1 block text-[9px] text-gray-600">{l}</span></div>)}</div></section>
  {msg&&<div className={`mt-5 rounded-2xl border p-4 text-sm font-bold ${msg.ok?"border-emerald-300/20 bg-emerald-500/[.07] text-emerald-300":"border-red-300/20 bg-red-500/[.07] text-red-300"}`}>{msg.text}</div>}
  {stage==="anonymous"&&<section className="mt-6 rounded-[28px] border border-cyan-300/15 bg-white/[.025] p-6 sm:p-8"><h2 className="text-xl font-black">لینک دعوتت را همین حالا بگیر</h2><p className="mt-3 text-xs leading-7 text-gray-400">فقط سه مورد زیر را تأیید کن. <b className="text-cyan-200">نیازی به کد ملی، شماره شبا یا امضای قرارداد نیست.</b> این‌ها فقط زمانی لازم می‌شوند که بخواهی درآمدت را نقدی برداشت کنی.</p>
   <div className="mt-5 space-y-2">{(data?.quickRules||[]).map((rule,index)=><label key={rule} className="flex items-start gap-3 rounded-2xl border border-white/[.07] bg-black/15 p-3.5 text-xs leading-6 cursor-pointer hover:border-cyan-400/25"><input type="checkbox" className="mt-1 accent-cyan-500" checked={quickChecks[index]||false} onChange={e=>setQuickChecks(quickChecks.map((v,j)=>j===index?e.target.checked:v))}/><span>{rule}</span></label>)}</div>
   <button onClick={start} disabled={busy||!quickChecks.length||quickChecks.some(v=>!v)} className="mt-5 w-full rounded-2xl bg-cyan-600 py-4 text-sm font-black disabled:opacity-40">دریافت لینک دعوت</button>
   <p className="mt-3 text-center text-[10px] text-gray-600">درآمدت از همان اولین مسابقه‌ی دوستت شروع به جمع‌شدن می‌کند.</p></section>}
  {stage!=="anonymous"&&showContract&&contract&&!contract.agreement&&<section className="mt-6 rounded-[28px] border border-amber-300/15 bg-white/[.025] p-5 sm:p-7"><h2 className="text-xl font-black">شرایط کسب درآمد از معرفی</h2><p className="mt-1 text-[10px] text-gray-600">نسخه {contract.version} · {contract.contentHash.slice(0,16)}…</p><button onClick={()=>window.print()} className="mt-4 rounded-xl border border-white/10 px-3 py-2 text-[10px] font-black">چاپ یا ذخیره PDF</button><pre className="mt-3 max-h-[500px] overflow-y-auto whitespace-pre-wrap rounded-2xl border border-white/[.08] bg-black/25 p-4 text-xs leading-7 text-gray-300">{contract.content}</pre><div className="mt-4 space-y-2">{contract.confirmations.map((t,i)=><label key={t} className="flex items-start gap-3 rounded-xl border border-white/[.06] p-3 text-xs leading-6"><input type="checkbox" className="mt-1 accent-cyan-500" checked={checks[i]||false} onChange={e=>setChecks(checks.map((v,j)=>j===i?e.target.checked:v))}/><span>{t}</span></label>)}</div><label className="mt-4 block text-xs text-gray-400">نام کامل امضاکننده<input className={`${inputClass} mt-2`} value={name} onChange={e=>setName(e.target.value)}/></label>{!otpSent?<button onClick={sendOtp} disabled={busy||checks.some(v=>!v)} className="mt-4 w-full rounded-2xl bg-amber-500 py-3.5 text-sm font-black text-black disabled:opacity-40">ارسال OTP قرارداد</button>:<div className="mt-4"><OtpCodeInput value={otp} onChange={setOtp} onComplete={(code)=>sign(code)} length={6} disabled={busy} verified={Boolean(contract?.agreement)} verifiedTitle="قرارداد امضا شد" verifiedSubtitle="حالا می‌توانی درآمدت را برداشت کنی" label="کد ۶ رقمی ارسال‌شده به ایمیلت را وارد کن؛ خودکار امضا می‌شود"/>{busy&&<p className="mt-3 text-center text-xs font-bold text-cyan-300">در حال تأیید...</p>}</div>}</section>}
  {stage!=="anonymous"&&partner&&<section className="mt-6 space-y-5"><div className="rounded-[28px] border border-white/[.08] bg-white/[.025] p-5 sm:p-7"><div className="flex items-center justify-between gap-3"><div><h2 className="text-xl font-black">لینک معرفی من</h2><p className="mt-1 text-xs text-gray-500">کد: <code>{partner.referralCode}</code></p></div><span className={`rounded-full px-3 py-1.5 text-[9px] font-black ${data?.live?"bg-emerald-500/10 text-emerald-300":"bg-amber-500/10 text-amber-300"}`}>{data?.rollout==="public"?"LIVE":data?.rollout==="canary"?"CANARY":"SHADOW"}</span></div><div className="mt-4 rounded-2xl bg-cyan-500/[.07] p-4"><code dir="ltr" className="block select-all break-all text-xs text-cyan-200">{partner.referralLink}</code><div className="mt-3 flex gap-2"><button type="button" onClick={()=>copyReferralLink(partner.referralLink)} className="rounded-xl bg-cyan-600 px-4 py-2 text-[10px] font-black active:scale-95">کپی لینک</button><a href={`https://t.me/share/url?url=${encodeURIComponent(partner.referralLink)}`} target="_blank" className="rounded-xl border border-white/10 px-4 py-2 text-[10px] font-black">اشتراک</a></div></div><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-5">{[[data?.stats?.totalReferrals||0,"کل افراد معرفی‌شده"],[data?.stats?.activeAttributions||0,"انتساب فعال"],[data?.stats?.qualifiedMatches||0,"Match پولی واجد"],[toman(lifetime),"کل درآمد واقعی"],[toman(available),"قابل برداشت"]].map(([v,l])=><div key={l} className="rounded-2xl bg-black/15 p-3"><strong className="block text-lg text-cyan-200">{typeof v==="number"?v.toLocaleString("fa-IR"):v}</strong><span className="text-[9px] text-gray-600">{l}</span></div>)}</div><p className="mt-3 text-xs text-gray-500">در انتظار آزادسازی ۷۲ساعته: <b className="text-amber-300">{toman(pending)}</b>{shadow>0&&<> · محاسبات Shadow قدیمی: <b>{toman(shadow)}</b></>}</p></div>
  {missing.length>0&&<div className="rounded-[24px] border border-amber-300/15 bg-amber-500/[.05] p-5"><h3 className="font-black text-amber-200">💰 برای برداشت نقدی چه چیزی مانده؟</h3><p className="mt-2 text-xs leading-6 text-gray-400">درآمدت از همین حالا جمع می‌شود و جایی نمی‌رود. این مراحل فقط برای <b>خارج‌کردن پول</b> لازم است و هر وقت خواستی می‌توانی انجامشان بدهی.</p>
   <ol className="mt-4 space-y-2">{missing.map((item,index)=><li key={item} className="flex items-center gap-3 rounded-xl bg-black/20 p-3 text-xs"><span className="grid h-6 w-6 shrink-0 place-items-center rounded-lg bg-amber-500/20 font-black text-amber-200">{(index+1).toLocaleString("fa-IR")}</span><span className="flex-1">{REQUIREMENT_LABELS[item]}</span>{item==="contract"&&<button onClick={()=>setShowContract(true)} className="shrink-0 rounded-lg bg-amber-500 px-3 py-1.5 text-[10px] font-black text-black">امضا</button>}{item==="national_id"&&<Link href="/profile/user" className="shrink-0 rounded-lg border border-white/15 px-3 py-1.5 text-[10px] font-black">تکمیل</Link>}</li>)}</ol></div>}

  <div className="grid gap-4 lg:grid-cols-2"><div className="rounded-[24px] border border-violet-300/10 bg-white/[.025] p-5"><h3 className="font-black">انتقال به اعتبار مسابقه</h3><p className="mt-2 text-xs leading-6 text-gray-500">تمام موجودی آزادشده فوراً به کیف پول بازی منتقل می‌شود؛ غیرقابل برداشت و غیرقابل برگشت است.</p>{!contract?.agreement&&<p className="mt-2 rounded-xl bg-black/25 p-2.5 text-[10px] leading-5 text-amber-200">برای انتقال اعتبار، یک‌بار باید قرارداد را امضا کنی.</p>}<button onClick={()=>contract?.agreement?redeem("gaming_wallet"):setShowContract(true)} disabled={busy||!data?.live||(Boolean(contract?.agreement)&&available<=0)} className="mt-4 w-full rounded-xl bg-violet-600 py-3 text-xs font-black disabled:opacity-40">{contract?.agreement?"انتقال به اعتبار Flexa":"امضای قرارداد"}</button></div><div className="rounded-[24px] border border-emerald-300/10 bg-white/[.025] p-5"><h3 className="font-black">برداشت نقدی</h3><p className="mt-2 text-xs leading-6 text-gray-500">حداقل ۲۰۰ هزار USDT؛ فقط به شبای معتبر صاحب حساب.</p><div className="mt-3 flex gap-2"><input dir="ltr" value={sheba} onChange={e=>setSheba(e.target.value.toUpperCase().replace(/\s/g,"").slice(0,26))} className={`${inputClass} text-left`} placeholder="IR..."/><button onClick={saveSheba} className="shrink-0 rounded-xl border border-white/10 px-3 text-[10px] font-black">ثبت شبا</button></div><p className="mt-2 text-[10px] text-gray-600">شبای ثبت‌شده: {partner.sheba||"ثبت نشده"}</p><button onClick={()=>redeem("cash")} disabled={busy||!data?.live||missing.length>0||available<BigInt(2_000_000)} className="mt-4 w-full rounded-xl bg-emerald-600 py-3 text-xs font-black disabled:opacity-40">درخواست برداشت نقدی</button></div></div></section>}
  {data?.payouts?.length?<section className="mt-5 rounded-[24px] border border-white/[.08] bg-white/[.025] p-5"><h3 className="font-black">سوابق انتقال و تسویه</h3><div className="mt-3 space-y-2">{data.payouts.map(p=><div key={p.id} className="flex items-center justify-between rounded-xl bg-black/20 p-3 text-xs"><span>{toman(p.amountRial)}</span><span className="text-gray-500">{p.destination==="gaming_wallet"?"اعتبار بازی":p.status}</span></div>)}</div></section>:null}
 </div><BottomNav/></main>;
}
