"use client";

import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import Navbar from "@/components/Navbar";
import { useAuth } from "@/contexts/AuthContext";

interface AdminData { partners: Array<Record<string, any>>; payouts: Array<Record<string, any>>; events: Array<Record<string, any>>; live: boolean; }

function toman(value: unknown) { try { return `${(BigInt(String(value || 0))/BigInt(10)).toLocaleString("fa-IR")} USDT`; } catch { return "—"; } }
function redact(value: string, start=3, end=3) { return value ? `${value.slice(0,start)}••••${value.slice(-end)}` : "—"; }

export default function AdminMediaPartnersPage() {
  const { user, loading } = useAuth();
  const [data,setData]=useState<AdminData|null>(null); const [busy,setBusy]=useState(""); const [error,setError]=useState("");
  const load=useCallback(async()=>{try{const r=await fetch("/api/admin/media-partners",{cache:"no-store",credentials:"include"});const j=await r.json();if(!r.ok)throw new Error(j.error);setData(j);}catch(e){setError(e instanceof Error?e.message:"خطا");}},[]);
  useEffect(()=>{if(user&&(user.role==="admin"||user.role==="super_admin"))load();},[user,load]);
  async function act(entity:string,id:string,action:string){const reason=action==="reject"||action==="suspend"||action==="terminate"?prompt("دلیل اقدام:")||"":"";let reference="";if(entity==="payout"&&action==="paid"){reference=prompt("شماره پیگیری پرداخت:")||"";if(!reference)return;}setBusy(`${entity}:${id}:${action}`);try{const r=await fetch("/api/admin/media-partners",{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json","X-Requested-With":"XMLHttpRequest"},body:JSON.stringify({entity,id,action,reason,reference})});const j=await r.json();if(!r.ok)throw new Error(j.error);await load();}catch(e){alert(e instanceof Error?e.message:"عملیات انجام نشد");}finally{setBusy("");}}
  if(loading||!user)return <main className="min-h-screen bg-[#07080d] text-white"><Navbar/><div className="py-32 text-center">در حال بررسی دسترسی...</div></main>;
  if(!["admin","super_admin"].includes(user.role))return <main className="min-h-screen bg-[#07080d] text-white"><Navbar/><div className="py-32 text-center">دسترسی ندارید</div></main>;
  return <main className="min-h-screen bg-[#07080d] pb-20 text-white" dir="rtl"><Navbar/><div className="mx-auto max-w-7xl px-4 py-8 sm:px-6">
    <div className="flex flex-wrap items-end justify-between gap-3"><div><span className="text-[9px] font-black tracking-[.22em] text-violet-400">AFFILIATE CONTROL</span><h1 className="mt-1 text-3xl font-black">مدیریت شرکای رسانه‌ای</h1><p className="mt-2 text-xs text-gray-500">وضعیت برنامه: <b className={data?.live?"text-emerald-300":"text-amber-300"}>{data?.live?"LIVE":"SHADOW MODE"}</b></p></div><div className="flex gap-2"><button onClick={load} className="rounded-xl border border-white/10 bg-white/[.04] px-4 py-2 text-xs font-black">بروزرسانی</button><Link href="/admin" className="rounded-xl bg-violet-600 px-4 py-2 text-xs font-black">پنل اصلی</Link></div></div>
    {error&&<div className="mt-5 rounded-xl bg-red-500/10 p-3 text-red-300">{error}</div>}
    <section className="mt-7"><h2 className="text-xl font-black">درخواست‌ها و رسانه‌ها</h2><div className="mt-4 grid gap-4 lg:grid-cols-2">{data?.partners.map(p=><article key={p.id} className="rounded-[24px] border border-white/[.08] bg-white/[.025] p-5"><div className="flex items-start justify-between gap-3"><div><h3 className="font-black">{p.mediaName}</h3><p className="mt-1 text-xs text-gray-500">{p.legalName} · {p.partnerType === "personal" ? "معرف عادی" : p.mediaType}</p></div><span className="rounded-lg bg-violet-500/10 px-2 py-1 text-[10px] font-black text-violet-300">{p.status}</span></div><a href={p.mediaUrl} target="_blank" rel="noreferrer" className="mt-3 block truncate text-xs text-cyan-300">{p.mediaUrl}</a>{p.ownershipProofUrl&&<a href={p.ownershipProofUrl} target="_blank" rel="noreferrer" className="mt-2 inline-block rounded-lg border border-white/10 px-2 py-1 text-[10px] text-violet-300">مشاهده مدرک مالکیت</a>}<div className="mt-3 grid grid-cols-2 gap-2 text-[10px] text-gray-400"><span>اعضا: {Number(p.followerCount||0).toLocaleString("fa-IR")}</span><span>کد: {p.referralCode}</span><span>ملی: {redact(p.nationalId)}</span><span>شبا: {redact(p.sheba,4,4)}</span></div>{p.rejectionReason&&<p className="mt-3 text-xs text-red-300">{p.rejectionReason}</p>}<div className="mt-4 flex flex-wrap gap-2">{p.status==="pending"&&<button disabled={!!busy} onClick={()=>act("partner",p.id,"approve")} className="rounded-xl bg-emerald-600 px-3 py-2 text-[10px] font-black">تأیید و فعال‌سازی</button>}{p.status==="active"&&<button disabled={!!busy} onClick={()=>act("partner",p.id,"suspend")} className="rounded-xl bg-amber-600 px-3 py-2 text-[10px] font-black">تعلیق</button>}{["pending","draft"].includes(p.status)&&<button disabled={!!busy} onClick={()=>act("partner",p.id,"reject")} className="rounded-xl bg-red-600 px-3 py-2 text-[10px] font-black">رد</button>}{["active","suspended"].includes(p.status)&&<button disabled={!!busy} onClick={()=>act("partner",p.id,"terminate")} className="rounded-xl border border-red-400/30 px-3 py-2 text-[10px] font-black text-red-300">خاتمه</button>}</div></article>)}</div></section>
    <section className="mt-10"><h2 className="text-xl font-black">درخواست‌های تسویه</h2><div className="mt-4 space-y-3">{data?.payouts.length?data.payouts.map(p=><div key={p.id} className="flex flex-col gap-3 rounded-2xl border border-white/[.08] bg-white/[.025] p-4 sm:flex-row sm:items-center"><div className="flex-1"><strong>{toman(p.amountRial)}</strong><span className="mr-3 text-xs text-gray-500">{p.status}</span><div className="mt-1 text-[10px] text-gray-600">{redact(p.shebaSnapshot,4,4)}</div></div><div className="flex gap-2">{p.status==="requested"&&<><button onClick={()=>act("payout",p.id,"approve")} className="rounded-xl bg-cyan-600 px-3 py-2 text-[10px] font-black">تأیید</button><button onClick={()=>act("payout",p.id,"reject")} className="rounded-xl bg-red-600 px-3 py-2 text-[10px] font-black">رد</button></>}{p.status==="approved"&&<button onClick={()=>act("payout",p.id,"paid")} className="rounded-xl bg-emerald-600 px-3 py-2 text-[10px] font-black">ثبت پرداخت</button>}</div></div>):<p className="text-sm text-gray-600">درخواست تسویه‌ای وجود ندارد.</p>}</div></section>
    <section className="mt-10"><h2 className="text-xl font-black">آخرین کمیسیون‌ها</h2><div className="mt-4 overflow-x-auto rounded-2xl border border-white/[.08]"><table className="w-full min-w-[700px] text-xs"><thead className="bg-white/[.04] text-gray-500"><tr><th className="p-3 text-right">Match</th><th className="p-3 text-right">مبلغ</th><th className="p-3 text-right">وضعیت</th><th className="p-3 text-right">قابل‌شدن</th></tr></thead><tbody>{data?.events.map(e=><tr key={e.id} className="border-t border-white/[.06]"><td className="p-3"><code>{String(e.matchId).slice(0,8)}</code></td><td className="p-3">{toman(e.totalAmountRial)}</td><td className="p-3">{e.status}</td><td className="p-3">{new Date(e.availableAt).toLocaleString("fa-IR")}</td></tr>)}</tbody></table></div></section>
  </div></main>;
}
